replicaCount: 1

name: "AWS Secrets Manager UI"
releaseName: aws-secrets-manager-ui

image:
  repository: ledongthuc/awssecretsmanagerui
  pullPolicy: IfNotPresent
  tag: "0.0.3"

imagePullSecrets: []
podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
