replicaCount: 1

name: AWS Secrets Manager UI

image:
  repository: ledongthuc/awssecretsmanagerui
  pullPolicy: IfNotPresent
  tag: "0.0.3"

imagePullSecrets: []
podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false

labels:
  app.kubernetes.io/name: "AWS Secrets Manager UI"
  app.kubernetes.io/instance: "aws-secrets-manager-ui"
nodeSelector: {}
tolerations: []
affinity: {}
