apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: "AWS Secrets Manager UI"
    app.kubernetes.io/instance: "aws-secrets-manager-ui"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- .Values.selectorLabels | nindent 4 }}
